baseURL = "https://www.brianz.page"
languageCode = "en-US"
title = "Brian Zbriger"
theme = "hugo-sustain"
googleAnalytics = "G-F8BW8D7W3P"

[params]
  avatar = "img/headshot.jpg"
  author = "Brian Zbriger"
  description = "Brian Zbriger's homepage"

[params.social]
  Github        = "BrianZbr"
  Email         = "mail@brianz.page"
  LinkedIn      = "brian-zbriger-70a31561"

[[menu.main]]
  name = "GitHub"
  identifier = "GitHub"
  weight = 100
  url = "https://github.com/BrianZbr/"

[[menu.main]]
  name = "LeetCode"
  identifier = "LeetCode"
  weight = 100
  url = "https://leetcode.com/BrianZbr/"

[[menu.main]]
  name = "LinkedIn"
  identifier = "LinkedIn"
  weight = 100
  url = "https://linkedin.com/in/brian-zbriger-70a31561"

[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 100
  url = "resume.pdf"

[[menu.main]]
  name = "email"
  identifier = "email"
  weight = 200
  url = "mailto:mail@brianz.page"
